name: Bandit Security Scan

on:
  push:
    branches:
      - main  # Run on push to the main branch (you can change this to another branch)
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  bandit_scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code to the GitHub runner

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set the Python version you are using

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit  # Install Bandit for security scanning

      - name: Run Bandit Scan
        uses: shundor/bandit-action@v1  # Use Bandit action for code scanning
        with:
          path: "."  # Path to the directory to scan (default is current directory)
          level: high  # Only report issues of 'high' severity or higher
          confidence: high  # Only report issues with 'high' confidence
          exit_zero: true  # Don't fail the build if issues are found
